### PR TITLE
Fix epidemic phase analysis

### LINKED ISSUE #125: Fix the epidemic phase analysis to be based on the phase the forecast date is in
## Problem
Currently assigning the epidemic phase to individual target end dates. What we actually want to do is assign them to the forecast date, and then evaluate all the horizons in that forecast date as in an epidemic phase. I had misinterpreted how to implement this.

### PR DESCRIPTION
**Pull request by kaitejohnson**
This PR closes #125. Instead of joining the epidemic phases by date, we instead left join to forecast date and location -- so any scores from a single forecast date and location are assigned a single epidemic phase corresponding to the phase assigned using the retrospective R(t) (so with future knowledge). 

Revised figures [here](https://github.com/cdcent/cfa-forecast-renewal-ww/issues/759#issuecomment-2258868022)

### CODE REVIEW

File: wweval/R/ms_fig4.R [hunk 1]
```diff
@@ -484,13 +485,36 @@ make_fig4_rel_crps_by_phase <- function(scores) {
     geom_hline(aes(yintercept = 1), linetype = "dashed") +
     xlab("Epidemic phase") +
     ylab("Relative CRPS") +
-    scale_y_continuous(trans = "log10") +
+    scale_y_continuous(trans = "log10", limits = c(0.5, 2)) +
     get_plot_theme(
       x_axis_title_size = 8,
       y_axis_title_size = 8
     ) +
     scale_fill_brewer(palette = "Set3")
```
Comment (dylanhmorris) [inline wweval/R/ms_fig4.R]: not for this PR, but worth creating a set palette for the phases too.

File: wweval/R/ms_fig4.R [hunk 2]
```diff
@@ -484,13 +485,36 @@ make_fig4_rel_crps_by_phase <- function(scores) {
...
+      position = position_dodge(width = 0.75),
+    ) +
+    xlab("Epidemic phase") +
+    ylab("CRPS") +
+    scale_y_continuous(limits = c(0.0, 1)) +
+    get_plot_theme(
+      x_axis_title_size = 8,
+      y_axis_title_size = 8
+    ) +
+    scale_fill_manual(values = colors$model_colors)
```
Comment (dylanhmorris) [inline wweval/R/ms_fig4.R]: If you want to hold onto this code within this file, it should be moved into a separate function (which just never gets called).

Related: I'd consider modularizing this function into a `compute_relative_crps` function and a `plot_relative_crps` function

Comment (dylanhmorris) [reply wweval/R/ms_fig4.R]: First point should be addressed in this PR, second doesn't have to be.

File: _targets_eval_postprocessing.R [hunk 3]
```diff
@@ -435,7 +435,7 @@ head_to_head_targets <- list(
         epidemic_phases,
         by = c(
           "location" = "state_abbr",
-          "date" = "reference_date"
+          "forecast_date" = "reference_date"
```
Comment (dylanhmorris) [inline _targets_eval_postprocessing.R]: question: why is the relevant date column of the `epidemic_phases` dataframe called `reference_date`? Is that what it's called in the source file or do we rename it that somewhere?

**Review by dylanhmorris — CHANGES_REQUESTED** [review]
Looks largely good. One key change and a couple suggestions/questions

File: wweval/R/ms_fig4.R (hunk 2 above)
Comment (kaitejohnson) [reply wweval/R/ms_fig4.R]: Yeah thats a good point. Will make a second PR for the `compute_relative_crps` fxns

File: _targets_eval_postprocessing.R (hunk 3 above)
Comment (kaitejohnson) [reply _targets_eval_postprocessing.R]: Ah yeah this is from the retrospective R(t) and I just kept NNH's nomenclature (they use reference date and report date). I can change it when `epidemic_phases` gets made though

File: wweval/R/ms_fig4.R (hunk 2 above)
Comment (kaitejohnson) [reply wweval/R/ms_fig4.R]: https://github.com/CDCgov/wastewater-informed-covid-forecasting/issues/131

File: _targets_eval_postprocessing.R (hunk 3 above)
Comment (kaitejohnson) [reply _targets_eval_postprocessing.R]: Fixed this

File: wweval/R/ms_fig4.R (hunk 1 above)
Comment (dylanhmorris) [reply wweval/R/ms_fig4.R]: #134

File: wweval/R/ms_fig4.R [hunk 4]
```diff
@@ -484,14 +486,78 @@ make_fig4_rel_crps_by_phase <- function(scores) {
...
       x_axis_title_size = 8,
       y_axis_title_size = 8
     ) +
-    scale_fill_brewer(palette = "Set3")
+    scale_fill_manual(values = colors$phase_colors)
+
+  return(p)
+}
+#' Make figure that plots distribution of crps scores stratified by
+#' epidemic phase
```
Comment (dylanhmorris) [inline wweval/R/ms_fig4.R:499]:
```suggestion
#' epidemic phase but aggregated across horizons
```

File: wweval/R/ms_fig4.R [hunk 5]
```diff
@@ -484,14 +486,78 @@ make_fig4_rel_crps_by_phase <- function(scores) {
...
+#' CRPS scores, colored by model, stratified by epidemic phase, across
+#' locations and forecast dates
+#' @export
+make_sfig_crps_by_phase <- function(scores) {
+  scores_w_fig_order <- scores |>
+    order_phases()
+
+  # Quick warning if there are NAs in epidemic phases
+  missing_phases <- scores |>
+    dplyr::filter(is.na(phase))
```
Comment (dylanhmorris) [inline wweval/R/ms_fig4.R:515]: This is supposed to reproduce the older plot that was aggregated across horizons within a location, yes? Perhaps I'm missing something, but I don't think it will. The code looks equivalent to the disaggregated main figure above.

**Review by dylanhmorris — CHANGES_REQUESTED** [review]

File: wweval/R/ms_fig4.R (hunk 5 above)
Comment (kaitejohnson) [reply wweval/R/ms_fig4.R:515]: I accidentally copied over the computing of the relative crps but it isn't being used. The difference here is that we are making the stathalfeye plot colored by model and with the y axis value by crps, instead of relative crps

File: wweval/R/ms_fig4.R (hunk 4 above)
Comment (kaitejohnson) [reply wweval/R/ms_fig4.R:499]: wait, these are not aggregated across horizons. They are just plots of the distribution of scores for each loc-forecast-date-day combination, without any summarizing across the horizon

File: wweval/R/ms_fig4.R (hunk 5 above)
Comment (dylanhmorris) [reply wweval/R/ms_fig4.R:515]: Got it, thanks!

File: wweval/R/ms_fig4.R [hunk 6]
```diff
@@ -484,14 +486,60 @@ make_fig4_rel_crps_by_phase <- function(scores) {
...
     get_plot_theme(
       x_axis_title_size = 8,
       y_axis_title_size = 8
     ) +
-    scale_fill_brewer(palette = "Set3")
+    scale_fill_manual(values = colors$phase_colors)
+
+  return(p)
+}
+#' Make figure that plots distribution of crps scores stratified by
```
Comment (dylanhmorris) [inline wweval/R/ms_fig4.R]:
```suggestion
#' Make figure that plots distribution of absolute crps stratified by
```

File: wweval/R/ms_fig4.R [hunk 7]
```diff
@@ -484,14 +486,60 @@ make_fig4_rel_crps_by_phase <- function(scores) {
...
+#' epidemic phase
+#'
+#' @param scores A tibble of scores by location, forecast date, date and model,
+#' containing the outputs of `scoringutils::score()` on samples plus metadata
+#' transformed into a tibble.
+#'
+#' @return A ggplot object containing plots of the distribution of
+#' CRPS scores, colored by model, stratified by epidemic phase, across
```
Comment (dylanhmorris) [inline wweval/R/ms_fig4.R]:
```suggestion
#' continuous ranked probability scores, colored by model, stratified by epidemic phase, across
```

**Review by dylanhmorris — APPROVED** [review]
LGTM. A couple wording tweaks you can take or leave.
